# Specify the base image
FROM node:18.16.1

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Specify the alternate entrypoint
ENTRYPOINT [ "node", "kernel", "asmx-cli" ]

# Specify the default command
CMD [ "node", "kernel", "./examples/hello.asmx" ]
